# Site settings
email: "me@geodavey.us"
description: "geoDavey geoSpatial"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://geoDavey.us" # the base hostname & protocol for your site

permalink: "/:categories/:slug"

exclude:
  - .cache
  - .sass-cache
  - .*

# Build settings
Markdown: kramdown

# SASS settings
sass:
  sass_dir: assets/css
  style: compressed
